# Welcome to Jekyll!
#

# Site settings
title: InCTF
description: 
 LEARN \| HACK \| WIN 
owner: teambi0s # or company name
#first_published: 2013 # if migrating another site, the year of your first publish
email: contact@inctf.in
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/teambi0s
  github: https://github.com/teambi0s
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/teambi0s
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: /contact/amritabi0s1@gmail.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
